// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Visualizador_de_Facturas_XML.Data;

#nullable disable

namespace Visualizador_de_Facturas_XML.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Visualizador_de_Facturas_XML.Models.Factura", b =>
                {
                    b.Property<string>("UUID")
                        .HasColumnType("TEXT");

                    b.Property<int>("PerfilID")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("XmlContent")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("UUID");

                    b.HasIndex("PerfilID");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("Visualizador_de_Facturas_XML.Models.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Perfiles");
                });

            modelBuilder.Entity("Visualizador_de_Facturas_XML.Models.Factura", b =>
                {
                    b.HasOne("Visualizador_de_Facturas_XML.Models.Perfil", "Perfil")
                        .WithMany("Facturas")
                        .HasForeignKey("PerfilID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Visualizador_de_Facturas_XML.Models.Perfil", b =>
                {
                    b.Navigation("Facturas");
                });
#pragma warning restore 612, 618
        }
    }
}
